"use client";

import Link from "next/link";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";

import type { ProjectSummary } from "@/modules/projects/project-types";

export function WorksClient({ projects }: { projects: ProjectSummary[] }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [combination, setCombination] = useState("all");
  const filtered = useMemo(() => projects.filter((project) => (status === "all" || project.status === status) && (combination === "all" || project.combination === combination) && `${project.title} ${project.description || ""}`.toLowerCase().includes(query.trim().toLowerCase())), [projects, query, status, combination]);
  return <><div className="mt-8 grid gap-3 rounded-2xl border border-slate-200 bg-white p-3 md:grid-cols-[1fr_170px_180px]"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input aria-label="搜索项目" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索项目名称或灵感" className="w-full rounded-xl bg-slate-50 py-2.5 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-indigo-100" /></label><label className="sr-only">状态<select value={status} onChange={(event) => setStatus(event.target.value)}><option>all</option></select></label><select aria-label="项目状态" value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl bg-slate-50 px-3 text-sm text-slate-600 outline-none"><option value="all">全部状态</option><option value="draft">灵感草稿</option><option value="review">待确认</option><option value="ready">已生成 Demo</option><option value="collaborating">协作中</option><option value="archived">已归档</option></select><select aria-label="输入组合" value={combination} onChange={(event) => setCombination(event.target.value)} className="rounded-xl bg-slate-50 px-3 text-sm text-slate-600 outline-none"><option value="all">全部输入</option><option value="text">文字</option><option value="melody">哼唱</option><option value="visual">视觉</option><option value="melody+text">文字 + 哼唱</option><option value="text+visual">文字 + 视觉</option><option value="melody+visual">哼唱 + 视觉</option><option value="melody+text+visual">全模态</option></select></div>{filtered.length ? <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((project) => <Link key={project.id} href={`/create/${project.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{project.combination}</span><span className="text-xs text-slate-400">{project.status}</span></div><h2 className="mt-5 truncate font-semibold text-slate-900">{project.title}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{project.description || "只有素材的灵感项目"}</p><p className="mt-5 text-xs text-slate-400">更新于 {new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium" }).format(new Date(project.updatedAt))}</p></Link>)}</section> : <section className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-medium">没有匹配的项目</h2><p className="mt-2 text-sm text-slate-500">试试修改关键词或筛选条件。</p></section>}</>;
}
